version: "3.8"
x-env: &api-url
  API_SERVER: http://static:8000

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    volumes:
      # init database and table
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - db
    environment:
      MYSQL_DATABASE: ai_english
      MYSQL_ROOT_PASSWORD: abc124

  # uwsgi
  api:
    build: .
    image: taishan-server:alpine
    volumes:
      - ./app:/taishan/app
      - ./static:/taishan/static
      - ./app.py:/taishan/app.py
      - ./uwsgi.ini:/etc/uwsgi/uwsgi.ini
    networks:
      - db
      - api
    depends_on:
      - db
    env_file: .env
    environment:
      UWSGI_SOCKET: 0.0.0.0:8000
      # override .env
      HOST: db
      PORT: 3306
      USER_NAME: root
      PASSWORD: abc124

  # static service and forward request to uwsgi
  static:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
      - ./static:/static
    ports:
      # port on 6000 can't use on Mac
      # https://stackoverflow.com/questions/4313403/why-do-browsers-block-some-ports/22622633#22622633
      - "8000:8000" # api
      - "7000:7000" # static
      - "80:80"
    expose:
      - "8000"
    # determine the order of service startup
    # https://docs.docker.com/compose/compose-file/#depends_on
    depends_on:
      - api
    networks:
      - api
      - web
    environment:
      UWSGI_SOCKET: api:8000
      SERVER_PORT: 8000
      FILE_SERVER_PORT: 7000

  # web app
  web:
    image: taishan-web:alpine
    ports:
      - "8090:80"
    networks:
      - web
    environment: *api-url

  # web for admin
  admin:
    image: taishan-admin:alpine
    ports:
      - "9000:80"
    networks:
      - web
    environment: *api-url

networks:
  db:
  api:
  web:
