@baseUrl = http://localhost:8080/admin

 
# @name login
POST {{baseUrl}}/user
content-type: application/json

{
    "username": "iron9527",
    "password": "abc1234569"
}

###
@authToken = {{login.response.body.data.token}}

###
GET {{baseUrl}}/crawl
X-Token: {{authToken}}


###
POST {{baseUrl}}/delete/news
X-Token: {{authToken}}

{
    "id": 44
}


### 

POST {{baseUrl}}/send/news
X-Token: {{authToken}}

{
    "id": 43
}