@baseUrl = http://{{host}}:{{port}}/admin

# local environment
# @name login
POST {{baseUrl}}/user
content-type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###
@authToken = {{login.response.body.data.token}}

###
GET {{baseUrl}}/crawl
X-Token: {{authToken}}

###
GET {{baseUrl}}/news
X-Token: {{authToken}}

###
POST {{baseUrl}}/delete/news
X-Token: {{authToken}}

{
    "id": 44
}


### 

POST {{baseUrl}}/send/news
X-Token: {{authToken}}

{
    "id": 65
}