@baseUrl = http://{{host}}:{{port}}/api

GET http://{{host}}:{{port}}

###
GET {{baseUrl}}/news

###
POST {{baseUrl}}/translate

{
    "q": "hello \n world"
}

###
POST {{baseUrl}}/news/detail

{
    "id": 65
}