@baseUrl = http://{{host}}:{{port}}/api

GET http://localhost:8080

###
GET {{baseUrl}}/news

###
GET {{baseUrl}}/news/59

###
POST {{baseUrl}}/translate

{
    "q": "hello \n world"
}

###
POST {{baseUrl}}/news/detail

{
    "id": 65
}