# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Crawl information

on:
  schedule:
    # At every 20th minute from 0 through 59 past every hour from 8 through 10
    # on every day-of-week from Sunday through Saturday.
    - cron: "0/20 0-2 * * 0-6"

jobs:
  build:
    runs-on: ubuntu-latest
    # choose an environment
    environment: crawl
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Crawl news
        run: |
          python -m app.spider.index
        env:
          # mysql
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          # qiniu
          QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
          QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
          QINIU_BUCKET_NAME: ${{ secrets.QINIU_BUCKET_NAME }}
          # dingding
          DINGDING_PUSH: ${{ secrets.DINGDING_PUSH }}
          DINGDING_TOKEN: ${{ secrets.DINGDING_TOKEN }}
          DINGDING_ROBOT_KEY: ${{ secrets.DINGDING_ROBOT_KEY }}
          # website
          WEB_APP_URL: ${{ secrets.WEB_APP_URL }}
          FILE_SERVER_URL: ${{ secrets.FILE_SERVER_URL }}
